#!/bin/bash

R='\033[0;31m'
G='\033[0;32m'
B='\033[0;33m'
Y='\033[0;33m'
NC='\033[0m'
COMPILE='cc *.c'

check() 
{
    echo -en "${Y}Exercise $1	${NC}"
    if [ -f ../ex$1/$2.c ]; then
        cc test$1.c ../ex$1/$2.c
		./a.out "$3" "$4"
		if [ $? = 0 ]; then
            echo -e "${G}OK${NC}"
        else
			if [ "$4" ]; then 
				echo -e "${R}Execution failed for input:${NC} ${Y}$3${NC}"
			fi
            echo -e "${R}KO${NC}"
        fi    
		rm a.out
	else
        echo -e "${R}Solution file not found${NC}"
    fi
}

check_diff()
{
	echo -en "${Y}Exercise $1	${NC}"
    if [ -f ../ex$1/$2.c ]; then
		cc test$1.c ../ex$1/$2.c
		./a.out "$4" "$5" > output
		if [ -f a.out ] && diff output "expected_output/$2($3)" > dump; then
			echo -e "${G}OK${NC}"
        else
			if [ "$4" ]; then 
				echo -e "	Execution failed for input: $4 $5" 
			fi
            echo -e "${R}KO${NC}"
        fi 
		rm a.out
	else
        echo -e "${R}Solution file not found${NC}"
    fi
}

########## NORMINETTE ##########
if [ $1 ] && [ $1 = '-n' ]; then
	# echo HELLO
	tar cf docasno.tar *.c
	rm *.c
	cd ..
	norminette
	cd _test
	tar xf docasno.tar
	rm docasno.tar
fi
################################

check 00 ft_iterative_factorial
check 01 ft_recursive_factorial
check 02 ft_iterative_power
check 03 ft_recursive_power
check 04 ft_fibonacci
check 05 ft_sqrt
check 06 ft_is_prime
check 07 ft_find_next_prime
check_diff 08 ft_ten_queens_puzzle 10
