#!/bin/bash

R='\033[0;31m'
G='\033[0;32m'
B='\033[0;33m'
Y='\033[0;33m'
NC='\033[0m'
COMPILE='cc *.c'

check() 
{
    echo -en "${Y}Exercise $1	${NC}"
    if [ -f ../ex$1/$2 ]; then
        cc test$1.c ../ex$1/$2
		./a.out
		exit_code=$?

		if [[ $exit_code == 0 ]]; then
            echo -e "${G}OK${NC}"
        else
            echo -e "${R}KO${NC}"
        fi    
	else
        echo -e "${R}Solution file not found"
    fi
}

tar cf docasno.tar *.c
rm *.c
cd ..
norminette
cd _test
tar xf docasno.tar
rm docasno.tar

check 00 ft_ft.c
check 01 ft_ultimate_ft.c
check 02 ft_swap.c
check 03 ft_div_mod.c
check 04 ft_ultimate_div_mod.c
check 05 ft_putstr.c
check 06 ft_strlen.c
check 07 ft_rev_int_tab.c
check 08 ft_sort_int_tab.c
